<a href="https://colab.research.google.com/github/ImeldaNasimiyu/Moringa_Week4/blob/main/Moringa_Data_Science_Prep_W4_Independent_Project_2021_05_Imelda_Nasimiyu_Python_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

AUTOLIB DATASET ANALYSIS

In [ ]:
#importing required libraries
import pandas as pd
import numpy as np

In [ ]:
#importing required dataset for AutoLib

Autolib_DF = pd.read_csv("Autolib_dataset.csv")
Autolib_DF.head(10)

                              Address  Cars  Bluecar counter  ...  day  hour  minute
0                 2 Avenue de Suffren     0                0  ...    8    11      43
1           145 Rue Raymond Losserand     6                6  ...    6     7      24
2    2 Avenue John Fitzgerald Kennedy     3                3  ...    3    20      14
3              51 Rue EugÃ¨ne OudinÃ©     3                3  ...    4     4      37
4  6 avenue de la Porte de Champerret     3                3  ...    8    17      23
5                8 Boulevard Voltaire     0                0  ...    6     7       2
6                      37 rue Leblanc     0                0  ...    8    18      20
7         17 Rue des Luaps ProlongÃ©e     3                3  ...    4    22      13
8               34 avenue Jean Moulin     1                1  ...    2    22      58
9        41 boulevard de Rochechouart     6                6  ...    4    15       2

[10 rows x 25 columns]

In [ ]:
Autolib_DF.isnull()

      Address   Cars  Bluecar counter  ...    day   hour  minute
0       False  False            False  ...  False  False   False
1       False  False            False  ...  False  False   False
2       False  False            False  ...  False  False   False
3       False  False            False  ...  False  False   False
4       False  False            False  ...  False  False   False
...       ...    ...              ...  ...    ...    ...     ...
4995    False  False            False  ...  False  False   False
4996    False  False            False  ...  False  False   False
4997    False  False            False  ...  False  False   False
4998    False  False            False  ...  False  False   False
4999    False  False            False  ...  False  False   False

[5000 rows x 25 columns]

In [ ]:
#Merging hour and minute to one column
Autolib_DF['time'] = (pd.to_datetime(Autolib_DF['hour'].astype(str) + ':' + Autolib_DF['minute'].astype(str), format='%H:%M')
          .dt.time)
Autolib_DF.head()

#Merging year, month and day into one column
Autolib_DF['date'] = (pd.to_datetime(Autolib_DF['year'].astype(str) + "/" + Autolib_DF["month"].astype(str) + "/" + Autolib_DF["day"].astype(str)))
Autolib_DF.head()

                              Address  Cars  ...      time       date
0                 2 Avenue de Suffren     0  ...  11:43:00 2018-04-08
1           145 Rue Raymond Losserand     6  ...  07:24:00 2018-04-06
2    2 Avenue John Fitzgerald Kennedy     3  ...  20:14:00 2018-04-03
3              51 Rue EugÃ¨ne OudinÃ©     3  ...  04:37:00 2018-04-04
4  6 avenue de la Porte de Champerret     3  ...  17:23:00 2018-04-08

[5 rows x 27 columns]

In [ ]:
#Dropping the extra columns
Autolib_DF = Autolib_DF.drop(['year','month','day','hour','minute'],axis=1).head()
Autolib_DF.head()

                              Address  Cars  ...      time       date
0                 2 Avenue de Suffren     0  ...  11:43:00 2018-04-08
1           145 Rue Raymond Losserand     6  ...  07:24:00 2018-04-06
2    2 Avenue John Fitzgerald Kennedy     3  ...  20:14:00 2018-04-03
3              51 Rue EugÃ¨ne OudinÃ©     3  ...  04:37:00 2018-04-04
4  6 avenue de la Porte de Champerret     3  ...  17:23:00 2018-04-08

[5 rows x 22 columns]

In [ ]:
#Updating the column['Cars'] to include sum of all 3 types of cars
Autolib_DF.Cars = Autolib_DF['Bluecar counter'] +  Autolib_DF['Utilib counter'] + Autolib_DF['Utilib 1.4 counter']   
Autolib_DF.head()

                              Address  Cars  ...      time       date
0                 2 Avenue de Suffren     0  ...  11:43:00 2018-04-08
1           145 Rue Raymond Losserand     6  ...  07:24:00 2018-04-06
2    2 Avenue John Fitzgerald Kennedy     5  ...  20:14:00 2018-04-03
3              51 Rue EugÃ¨ne OudinÃ©     4  ...  04:37:00 2018-04-04
4  6 avenue de la Porte de Champerret     3  ...  17:23:00 2018-04-08

[5 rows x 22 columns]

In [ ]:
#Updating dataframe to include usage computation to determine whether the car was picked up, returned, or nothing happened.
#Car returned
Autolib_DF['Returned'] = Autolib_DF['Cars'] - Autolib_DF['Slots']
Autolib_DF.head(10)

                              Address  Cars  ...       date  Returned
0                 2 Avenue de Suffren     0  ... 2018-04-08        -2
1           145 Rue Raymond Losserand     6  ... 2018-04-06         6
2    2 Avenue John Fitzgerald Kennedy     5  ... 2018-04-03         4
3              51 Rue EugÃ¨ne OudinÃ©     4  ... 2018-04-04         2
4  6 avenue de la Porte de Champerret     3  ... 2018-04-08         0

[5 rows x 23 columns]

In [ ]:
#Car in use / Also equal to slots
Autolib_DF['operational'] = Autolib_DF['Cars'] - Autolib_DF['Returned']
Autolib_DF.head(10)

                              Address  Cars  ...  Returned  operational
0                 2 Avenue de Suffren     0  ...        -2            2
1           145 Rue Raymond Losserand     6  ...         6            0
2    2 Avenue John Fitzgerald Kennedy     5  ...         4            1
3              51 Rue EugÃ¨ne OudinÃ©     4  ...         2            2
4  6 avenue de la Porte de Champerret     3  ...         0            3

[5 rows x 24 columns]

In [ ]:
#Car idle
# Autolib_DF['idle'] = Autolib_DF['operational'] - Autolib_DF['Slots']
# Autolib_DF.head(10)

DATA ANALYSIS

Identify the most popular hour of the day for picking up a shared electric car (Bluecar) in the city of Paris over the month of April 2018.

In [97]:
# Autolib_DF.iloc([Autolib_DF['operational'].idxmax() & Autolib_DF['Bluecar counter'] > 0 ])
# Autolib_DF[Autolib_DF.operational == Autolib_DF.operational.max()]
# Autolib_DF[Autolib_DF['Bluecar counter'].max()]
# Autolib_DF[Autolib_DF['Bluecar counter'] == Autolib_DF['Bluecar counter'].max() & Autolib_DF.operational >0 ]
# result = Autolib_DF[(Autolib_DF['Bluecar counter']>0) & (Autolib_DF.operational.max())]
# result
# result = result[(result['var']>0.25) | (result['var']<-0.25)]
# Autolib_DF.loc[Autolib_DF[Autolib_DF.operational == Autolib_DF.operational.max()] & (Autolib_DF[Autolib_DF['Bluecar counter'] > 0 ]) ]
# Autolib_DF.loc[(Autolib_DF['operational'].max() == Autolib_DF['operational']) & (Autolib_DF['Bluecar counter'] > 0)]

Autolib_DF[(Autolib_DF['Bluecar counter'] == Autolib_DF['Bluecar counter'].max() ) & (Autolib_DF['operational'] > 0)]

groupby_bluecar = Autolib_DF['operational'].groupby(Autolib_DF['Bluecar counter'])
groupby_bluecar

groupby_bluecar.max()

pd.pivot_table(Autolib_DF, index=['Bluecar counter','operational', 'time'], aggfunc='max')

                                                                 Address  ...       date
Bluecar counter operational time                                          ...
0               2           11:43:00                 2 Avenue de Suffren  ... 2018-04-08
3               1           20:14:00    2 Avenue John Fitzgerald Kennedy  ... 2018-04-03
                2           04:37:00              51 Rue EugÃ¨ne OudinÃ©  ... 2018-04-04
                3           17:23:00  6 avenue de la Porte de Champerret  ... 2018-04-08
6               0           07:24:00           145 Rue Raymond Losserand  ... 2018-04-06

[5 rows x 19 columns]

What is the most popular hour for returning cars?

In [ ]:
#  Autolib_DF['Returned'].max()
Autolib_DF[Autolib_DF.Returned == Autolib_DF.Returned .max()].head(1)

                     Address  Cars  ...  Returned  operational
1  145 Rue Raymond Losserand     6  ...         6            0

[1 rows x 24 columns]

What station is the most popular?
Overall?
At the most popular picking hour?

In [93]:
# Autolib_DF[Autolib_DF.operational == Autolib_DF.operational.max()].head(1)
groupby_station = Autolib_DF['operational'].groupby(Autolib_DF['Address'])
groupby_station

groupby_station.max()

Address
145 Rue Raymond Losserand             0
2 Avenue John Fitzgerald Kennedy      1
2 Avenue de Suffren                   2
51 Rue EugÃ¨ne OudinÃ©                2
6 avenue de la Porte de Champerret    3
Name: operational, dtype: int64

What postal code is the most popular for picking up Blue cars? Does the most popular station belong to that postal code?
Overall?
At the most popular picking hour?

In [98]:
pd.pivot_table(Autolib_DF, index=['Postal code','operational', 'Bluecar counter'], aggfunc='max')

                                                                    Address  ...      time
Postal code operational Bluecar counter                                      ...
75013       2           3                            51 Rue EugÃ¨ne OudinÃ©  ...  04:37:00
75014       0           6                         145 Rue Raymond Losserand  ...  07:24:00
75015       2           0                               2 Avenue de Suffren  ...  11:43:00
75017       3           3                6 avenue de la Porte de Champerret  ...  17:23:00
93350       1           3                  2 Avenue John Fitzgerald Kennedy  ...  20:14:00

[5 rows x 19 columns]

Do the results change if you consider Utilib and Utilib 1.4 instead of Blue cars?

In [99]:
#No results do not change
pd.pivot_table(Autolib_DF, index=['Postal code','operational', 'Utilib counter'], aggfunc='max')

                                                                   Address  ...      time
Postal code operational Utilib counter                                      ...
75013       2           1                           51 Rue EugÃ¨ne OudinÃ©  ...  04:37:00
75014       0           0                        145 Rue Raymond Losserand  ...  07:24:00
75015       2           0                              2 Avenue de Suffren  ...  11:43:00
75017       3           0               6 avenue de la Porte de Champerret  ...  17:23:00
93350       1           0                 2 Avenue John Fitzgerald Kennedy  ...  20:14:00

[5 rows x 19 columns]